### ISSUE TITLE
Add onset detection based on the accentuation feature code

### ISSUE THREAD

**Issue by jimearruti** [mrocamora/carat#16]

**Comment by mrocamora** [comment]
I have just added the peak_detection function to features.py. It is used to select peaks of the accentuation functions as onset candidates. Everything else needed is already implemented. I should add some examples on how to do onset detection.

**Comment by mrocamora** [comment]
Should we add a module called onsets to do this that uses the functions in features.py? Or should we put the onset detection directly in the features.py? I think the former is the best option. But this implies moving peak_detection out of features.py, to onsets.py or util.py. 

Then we should also add some sort of template for particular type of onsets (i.e. chico, piano, repique, clave, tamborim).
