### ISSUE TITLE
Fix RuntimeWarning in carat_microtiming_patterns_demo

### ISSUE THREAD

**Issue by jimearruti** [mrocamora/carat#7]
In the _Load onsets and align beats to closest onsets_ section, a RuntimeWarning is shown when running the first cell.

(...)/carat/carat/microtiming.py:104: RuntimeWarning: Mean of empty slice
  beats = np.nanmean(onsets_at_beats, axis=0)

Edit: this can also be seen when running _microtiming_align_beats_to_onsets.py_ : 
_python microtiming_align_beats_to_onsets.py ../carat/example_data/candombe/Take_211_chico.wav ../carat/example_data/candombe/Take_211_chico_beats.csv ../carat/example_data/candombe/Take_211_chico_onsets.csv_

**Comment by mrocamora** [comment]
It is caused by taking the mean of a single value. It's an easy fix.
